"""
NHID-Clinical – Pilot Report Generator
========================================
Generates a markdown compliance report from a directory of per-call
conformance result JSON files collected during a 30/60/90-day shadow pilot.

Each input file is one call's API conformance response (the exact JSON
returned by POST /v1/demo/check or the vendor adapter routes), optionally
extended with "session_id" and "timestamp":

  {
    "session_id": "call_001",
    "timestamp": "2026-06-01T10:00:00Z",
    "conformant": true,
    "action": "ALLOW",
    "cas": {"score": 0.9, "tier": "Verified Trust", ...},
    "violations": []
  }

Usage:
  python tools/pilot_report_generator.py <results_dir> [output.md]

NHID-Clinical is a voluntary open proposal. CC BY 4.0.
Not an accredited standard. Not a regulatory requirement.
"""

from __future__ import annotations

import json
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

CONTROLS = ("IDG-01", "PDX-01", "DBC-01", "EIT-01", "ATR-01")


def load_results(results_dir: str | Path) -> list[dict[str, Any]]:
    """Load every *.json file in the directory as one conformance result."""
    directory = Path(results_dir)
    if not directory.is_dir():
        raise ValueError(f"Not a directory: {results_dir}")

    results = []
    for path in sorted(directory.glob("*.json")):
        try:
            with open(path) as fh:
                data = json.load(fh)
        except (json.JSONDecodeError, OSError):
            continue  # skip unreadable files rather than abort the report
        if isinstance(data, dict) and "conformant" in data:
            data.setdefault("session_id", path.stem)
            results.append(data)
    return results


def summarize(results: list[dict[str, Any]]) -> dict[str, Any]:
    """Aggregate pilot metrics from a list of conformance results."""
    total = len(results)
    passed = sum(1 for r in results if r.get("conformant"))

    cas_scores = [
        r["cas"]["score"]
        for r in results
        if isinstance(r.get("cas"), dict) and isinstance(r["cas"].get("score"), (int, float))
    ]

    violation_counts: Counter = Counter()
    for r in results:
        for v in r.get("violations", []):
            rule = v.get("rule_id", "UNKNOWN")
            violation_counts[rule] += 1

    return {
        "calls_total": total,
        "calls_passed": passed,
        "pass_rate": round(passed / total, 4) if total else 0.0,
        "cas_avg": round(sum(cas_scores) / len(cas_scores), 4) if cas_scores else 0.0,
        "cas_min": round(min(cas_scores), 4) if cas_scores else 0.0,
        "cas_max": round(max(cas_scores), 4) if cas_scores else 0.0,
        "violations_by_rule": dict(violation_counts),
    }


def generate_report(results: list[dict[str, Any]], org_name: str = "Pilot Organization") -> str:
    """Render a markdown compliance report from conformance results."""
    s = summarize(results)
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    lines = [
        f"# NHID-Clinical Shadow Pilot Report — {org_name}",
        "",
        f"Generated {today} · NHID-Clinical v1.3 · voluntary open baseline (CC BY 4.0)",
        "",
        "## Summary",
        "",
        "| Metric | Value |",
        "| :--- | :--- |",
        f"| Total calls evaluated | {s['calls_total']} |",
        f"| Conformant calls | {s['calls_passed']} |",
        f"| Pass rate | {s['pass_rate']:.1%} |",
        f"| Average CAS | {s['cas_avg']:.4f} |",
        f"| CAS range | {s['cas_min']:.4f} – {s['cas_max']:.4f} |",
        "",
        "## Violations by Control",
        "",
        "| Control | Violations |",
        "| :--- | ---: |",
    ]

    for control in CONTROLS:
        lines.append(f"| {control} | {s['violations_by_rule'].get(control, 0)} |")
    for rule, count in sorted(s["violations_by_rule"].items()):
        if rule not in CONTROLS:
            lines.append(f"| {rule} | {count} |")

    lines += [
        "",
        "## Per-Call Results",
        "",
        "| Session | Conformant | CAS | Violations |",
        "| :--- | :--- | ---: | :--- |",
    ]
    for r in results:
        cas = r.get("cas", {})
        score = cas.get("score", "—") if isinstance(cas, dict) else "—"
        rules = ", ".join(v.get("rule_id", "?") for v in r.get("violations", [])) or "—"
        lines.append(
            f"| {r.get('session_id', '?')} | {'✅' if r.get('conformant') else '❌'} | {score} | {rules} |"
        )

    lines += [
        "",
        "---",
        "",
        "NHID-Clinical is a voluntary open proposal — not an accredited standard, "
        "not a regulatory requirement. Report generated by `tools/pilot_report_generator.py`.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) < 2:
        print("Usage: python tools/pilot_report_generator.py <results_dir> [output.md]")
        return 1

    results = load_results(sys.argv[1])
    report = generate_report(results)

    if len(sys.argv) >= 3:
        out_path = sys.argv[2]
    else:
        out_path = f"pilot_report_{datetime.now(timezone.utc).strftime('%Y-%m-%d')}.md"

    Path(out_path).write_text(report)
    print(f"Wrote {out_path} ({len(results)} calls)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
